#!/usr/bin/env ruby

require 'text-gen'
require 'slop'

begin
  opts = Slop.parse do |o|
    o.integer '-c', '--count',
              'number of names to generate (default: 5)',
              default: 5
    o.string  '-p', '--prefix'
    o.bool    '-h', '--help',
              'print help and exit'
    o.on      '-v', '--version', 'print version and exit' do
      puts "CMDNAMES v#{TextGen::VERSION}"
      exit
    end
  end
rescue Slop::Error => e
  puts e.message
  exit
end


if opts.help?
  puts opts
  exit
end

puts TextGen.rand_command_name(opts[:count], opts[:prefix])