#!/usr/bin/env ruby

require 'command_names'
require 'slop'

# TODO(feature): Add color for errors

begin
  opts = Slop.parse do |o|
    o.integer '-c', '--count',
              'number of ids to generate (default: 5)',
              default: 5
    o.bool    '-h', '--help',
              'print help and exit'
    o.on      '-v', '--version', 'print version and exit' do
      puts "PROTOIDS v#{CommandNames::VERSION}"
      exit
    end
  end
rescue Slop::Error => e
  puts e.message
  exit
end


if opts.help?
  puts opts
  exit
end

puts CommandNames.rand_prototype_id opts[:count]